### ISSUE TITLE
Live demo

### ISSUE THREAD

**Issue by CountNick** [MarjoleinAardewijn/progressive-web-apps-1920#7]
I noticed a link to a live demo, but when i clicked the link it didn't take me to the live demo. If you still need to deploy your app you might want to look into a tool like [Heroku](https://dashboard.heroku.com/) or [Netlify](https://www.netlify.com/):clown_face:

**Comment by StefanGerrits2** [comment]
@CountNick `Netlify` won't work with dynamic data. You probably want to use `Heroku` or `Zeit Now`

**Comment by MarjoleinAardewijn** [comment]
I'm trying to deploy my app with `Heroku`, but I keep getting the following error message:
<img width="1920" alt="Screenshot 2020-03-16 at 22 03 03" src="https://user-images.githubusercontent.com/23479038/76799546-0604ea80-67d2-11ea-8c73-b13931cd6163.png">

**Comment by CountNick** [comment]
It seems like heroku is still taking the localhost port 3000

**Comment by CountNick** [comment]
https://github.com/MarjoleinAardewijn/progressive-web-apps-1920/blob/32eb1d28114668879719a3afb0afe4b465bf31b4/config.js#L6

You can try changing this line of code to:
```js
port: process.env.PORT || 3000
```
So if there is no env port available it wil listen to port 3000 and the other way around.

**Comment by MarjoleinAardewijn** [comment]
Thanks for your help! And that is a great fallback! I will certainly try to implement that as well! 

For now I fixed this issue by giving my URI to the static folder in my `rimraf` command relative to the root directory (root directory (`/`) instead of current directory (`./`) and for some URIs referencing to the parent directory (`../`) as well). To prevent this problem with other URIs I refactored them all so that they all are relative to the root directory.
